### ISSUE TITLE
StartShift automatico si el servidor no le da un OpenShift

### ISSUE THREAD

**Issue by juansmolano** [nebulae-tpi/driver-app#1]
Si el app esta corriendo con un Shift disponible, si por debajo se borra el shift en BD, cuando se presiona AVAILABLE/NO_AVAILABE el app se da cuenta que no tiene shift, vuelve a la pagina de login.

y parece que por tener JWT valido automaticamente crea un nuevo shift y empieza a operar.

El problema es que se pide que si un movil se logea con la misma cuenta, y se cierra un shift para inicar el otro, entonces quedaria en un loop infinito entre los dos moviles.

Este compartiamiento se debe hablar para poder saber si se separa en la ui el concepto de login y shift, o se siguen fucionando entonces al irse el shift se va el token tambine

**Comment by Drimax2010** [comment]
Se identificó que en el momento en el que se realiza una conexión exitosa con MQTT,  se consulta si hay un turno abierto. Lo que causa que cuando se finalice el turno y se pierda conexión con MQTT se consulte el openShift y si lo encuentra inicia sesión con este, en caso contrario intenta iniciar un nuevo shift. Debido a esto solo se va a consultar el openShift luego de tener una conexión exitosa si y solo si el cliente ha solicitado iniciar sesión (solo afecta el LoginActivity)
