### ISSUE TITLE
comportamiento extrano login

### ISSUE THREAD

**Issue by juansmolano** [nebulae-tpi/driver-app#2]
si el vehiculo tiene multiple vehiculos, y se demora para seleccionar un vehiculo, parece que el login de fondo da timeout, entonce svuelve a login

![screenshot_20190210-144908_driver](https://user-images.githubusercontent.com/8793032/52538748-4fb81180-2d44-11e9-84b6-36833b70bb81.jpg)
![screenshot_20190210-144917_driver](https://user-images.githubusercontent.com/8793032/52538749-4fb81180-2d44-11e9-8d84-65cda65e5b53.jpg)
![screenshot_20190210-144923_driver](https://user-images.githubusercontent.com/8793032/52538750-5050a800-2d44-11e9-9e12-75dcc3d5536b.jpg)

**Comment by juansmolano** [comment]
... y de no escoger un carro, dar atras o cerrar el app.  la aplicacion queda en un estado indeterminado por un largo tiempo .....

**Comment by Drimax2010** [comment]
La causa de esto es que no se estaba verificando si se tenia un turno para identificar si la sesión era valida (solo hacia falta tener un token valido y vigente). Actualmente se valida tanto el token como el turno para permitir el acceso al app
