### ISSUE TITLE
App en background parece no enviar ubicacion

### ISSUE THREAD

**Issue by juansmolano** [nebulae-tpi/driver-app#3]
Realizando pruebas teniendo en el mismo celular el satelite y driver-app en un viaje de 11km, se nota que cuando la app-driver esta en segundo plano deja de enviar ubicacion.

**Comment by Drimax2010** [comment]
Tal y como se descibe en la documentación oficial de Android, se han limitado los escuchadores de ubicacón para que solo se reporte unas pocas veces cada hora en las versiones 8 y superiores (https://developer.android.com/about/versions/oreo/background-location-limits?hl=es-419)
Por lo que se ha tomado la decisión de implementar un servicio en primer plano y así tener los escuchadores siempre activos, adicional a esto por buenas practicas se ha incrementado el intervalo de tiempo en el que se esuchan los cambios de gps (anteriormente de 2 a 4 segundos, ahora de 20 a 30 segundos) 

Se debe hacer seguimiento al último cambio mencionado y si llega a generar problemas se debe abrir un nuevo reporte.
